version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db  # Cambiado de 'localhost' a 'db'
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=techeduplanet
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ejemplo
      MYSQL_DATABASE: mydb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:

