version: '3.8'
services:
  app:
    build: .
    ports:
      - "3001:3001"  # Cambiado de 3000:3000 a 3001:3001
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=techeduplanet
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: techeduplanet
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
